name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Up docker contianers
        run: |
          docker compose up -d --build
          docker compose ps -a

      - name: Init
        run: |
          docker compose exec laravel cp .env.example .env
          docker compose exec laravel composer install
          docker compose exec laravel php artisan migrate

      - name: Run lint
        run: |
          docker compose exec laravel composer larastan

      - name: Run test
        run: |
          docker compose exec laravel php artisan test
