name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Up docker container
        run: |
          docker compose up -d --build laravel

      - name: Init
        run: |
          docker compose exec laravel composer install

      - name: Run lint
        run: |
          docker compose exec laravel composer larastan

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Up docker container
        run: docker compose up -d --build laravel db

      - name: Init
        run: docker compose exec laravel composer install

      - name: Run test
        run: docker compose exec laravel composer test
